[workspace]
members = [
    "mwdg",
    "mwdg-ffi",
]
resolver = "3"

[workspace.package]
version = "0.3.0"
license = "MIT OR Apache-2.0"
authors = ["Vladimir Petrigo <vladimir.petrigo@gmail.com>"]
repository = "https://github.com/vpetrigo/mwdg"
